---
# Common tasks for all Kubernetes nodes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
  become: true

- name: Disable swap and remove from fstab
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  when: disable_swap
  become: true

- name: Enable kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter
  become: true

- name: Configure kernel parameters for Kubernetes
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
  become: true

- name: Create directory for Kubernetes apt key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Kubernetes apt key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    mode: '0644'
  become: true

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes
  become: true

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
  become: true

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
  become: true

- name: Configure containerd
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  become: true

- name: Update containerd configuration to use systemd cgroup driver
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '(\s+)SystemdCgroup = false'
    line: '\1SystemdCgroup = true'
    backrefs: yes
  become: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet={{ kubernetes_package_version }}
      - kubeadm={{ kubernetes_package_version }}
      - kubectl={{ kubernetes_package_version }}
    state: present
  become: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
  become: true
